export default {
  background: {
    default: "#fafafa",
    paper: "#fff",
    paperDark: "rgba(0, 0, 0, 0.38)",
    hover: "#f0f0f0",
    active: "#f0f0f0",
  },
  border: {
    light: "#ddd",
  },
  text: {
    primary: "rgba(0, 0, 0, 0.87)",
    secondary: "rgba(0, 0, 0, 0.54)",
    disabled: "rgba(0, 0, 0, 0.38)",
    with: "##757575cc",
    withDark: "#757575cc",
  },
  palette: {
    mode: "light",
    primary: {
      main: "#6a80ff",
      light: "#6a80ff",
      dark: "#6a80ff",
    },
    secondary: {
      main: "#bf54ed",
      light: "#bf54ed",
      dark: "#bf54ed",
    },
  },

  device: {
    mobile: "@media only screen and (max-width: 480px)",
    tablet: "@media only screen and (max-width: 768px)",
    laptop: "@media only screen and (max-width: 1024px)",
    desktop: "@media only screen and (max-width: 2560px)",
  },

  efects: {
    linearGradiente:
      "linear-gradient(136deg, #6a80ff 0%, #bf54ed 50%, #580089 100% )",
  },

  typography: {
    fontFamily: "'Lato', sans-serif",
    fontSize: 14,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
    h1: {
      fontSize: "2rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h2: {
      fontSize: "2rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h3: {
      fontSize: "1.5rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h4: {
      fontSize: "1.5rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h5: {
      fontSize: "1.25rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    h6: {
      fontSize: "1.2rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    subtitle1: {
      fontSize: "1rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    subtitle2: {
      fontSize: "0.875rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    body1: {
      fontSize: "1rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    body2: {
      fontSize: "0.875rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    button: {
      fontSize: "0.875rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    caption: {
      fontSize: "0.75rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
    overline: {
      fontSize: "0.625rem",
      fontWeight: 300,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
    },
  },
};
